using SD.Domain.Entities.Provisioning.Control_OC.Apn;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace SD.Application.Provisioning.Control_OC.OC.DTOs
{
	public class GetOC
	{
		public record GetOcDTO(int Id,
										DateOnly? Fecha,
										string? Oc,
										string? Os,
										string? Circuito,
										string? Cliente,
										string Actividad,
										string? Bw,
										string? Bws,
										string Producto,
										string? NodoAcceso,
										string? PuertoAcceso,
										string? UplinkAcceso,
										string? VlanAcceso,
										string? PuertoTransIn,
										string? TxInTrans,
										string? TxOutTrans,
										string? PuertoTransOut,
										string? EquipoAg,
										string? TipoPuertoAg,
										string? PuertoAg,
										string? VpnAg,
										string? IpPrefix,
										string? IpIspAg,
										string? IpIspMask,
										string? IpClienteWAg,
										string? IpClienteWMask,
										string? Ttk,
										string? FechaSolicitudIng,
										string? FechaRespuestaIng,
										string? DescripOc,
										string? Descripcion,
										string? Estatus,
										string? TipoServicio,
										string? IdGrado,
										string? Template,
										string? UsuarioCreo,
										string? GPON_P2P,
										string? LoopBack,
										string? CreateLoopBack,
										string? CreateVPN,
										string? RouterRD,
										string? PON,
										string? PosicionOnt,
										string? NombreFactura,
										string? NumeroCuenta,
										string? ClienteRutaEstatica,
										string? Plan,
										string? MangaGPON, //GPON
										string? GestionIpP2P,
										string? GestionVlanP2P,
										string? GestionIpSwitch,
										string? GestionIpRouter,
										string? GestionPrimeraMultiVlan,
										string? GestionSegundaMultiVlan,
										string? PuertoMG,
										string? CoordenadasClienteY, //Coordenadas Cliente solo para los casos de instalación y traslado
										string? CoordenadasClienteX, //Coordenadas Cliente solo para los casos de instalación y traslado
										string? CoordenadasMangaY, //Coordenadas de Manga solo para GPON
										string? CoordenadasMangaX, //Coordenadas de Manga solo para GPON
										string? Site, //FO P2P
										string? Serial_ONT);

		public record GetOcIntAsym1IPDTO(int Id,
										DateOnly? Fecha,
										string? Oc,
										string? Os,
										string? Circuito,
										string? Cliente,
										string Actividad,
										string? Bw,
										string? Bws,
										string Producto,
										string? NodoAcceso,
										string? PuertoAcceso,
										string? UplinkAcceso,
										string? EquipoAg,
										string? TipoPuertoAg,
										string? PuertoAg,
										string? VpnAg,
										string? Prefix,
										string? IpIspAg,
										string? IpIspMask,
										string? IpClienteWAg,
										string? IpClienteWMask,
										string? Ttk,
										string? FechaSolicitudIng,
										string? FechaRespuestaIng,
										string? DescripOc,
										string? Descripcion,
										string? Estatus,
										string? TipoServicio,
										string? IdGrado,
										string? Template,
										string? UsuarioCreo,
										string? GPON_P2P,
										string? LoopBack,
										string? CreateLoopBack,
										string? CreateVPN,
										string? RouterRD,
										string? PON,
										string? PosicionOnt,
										string? NombreFactura,
										string? NumeroCuenta,
										string? ClienteRutaEstatica,
										string? Plan,
										string? MangaGPON, //GPON
										string? PuertoMG,
										string? CoordenadasClienteY, //Coordenadas Cliente solo para los casos de instalación y traslado
										string? CoordenadasClienteX, //Coordenadas Cliente solo para los casos de instalación y traslado
										string? CoordenadasMangaY, //Coordenadas de Manga solo para GPON
										string? CoordenadasMangaX, //Coordenadas de Manga solo para GPON
										string? Site, //FO P2P
										string? Serial_ONT);

		public record GetOcAPNDTO(int Id,
								DateOnly? Fecha,
								string? Oc,
								string? Os,
								string? Circuito,
								string? Cliente,
								string Actividad,
								string? Bw,
								string? Bws,
								string Producto,
								string? NodoAcceso,
								string? PuertoAcceso,
								string? UplinkAcceso,
								string? EquipoAg,
								string? TipoPuertoAg,
								string? PuertoAg,
								string? VpnAg,
								string? Prefix,
								string? IpIspAg,
								string? IpIspMask,
								string? IpClienteWAg,
								string? IpClienteWMask,
								string? Ttk,
								string? FechaSolicitudIng,
								string? FechaRespuestaIng,
								string? DescripOc,
								string? Descripcion,
								string? Estatus,
								string? TipoServicio,
								string? IdGrado,
								string? Template,
								string? UsuarioCreo,
								string? GPON_P2P,
								string? LoopBack,
								string? RouterRD,
								string? PON,
								string? PosicionOnt,
								string? NombreFactura,
								string? NumeroCuenta,
								string? Plan,
								string? Serial_ONT,
								string? ApnId,
								TbApn? ApnData);

		public record GetOcSIPDatosDTO(int Id,
										DateOnly? Fecha,
										string? Oc,
										string? Os,
										string? Circuito,
										string? Cliente,
										string Actividad,
										string? Bw,
										string? Bws,
										string Producto,
										string? NodoAcceso,
										string? PuertoAcceso,
										string? UplinkAcceso,
										string? EquipoAg,
										string? TipoPuertoAg,
										string? PuertoAg,
										string? VpnAg,
										string? Prefix,
										string? IpIspAg,
										string? IpIspMask,
										string? IpClienteWAg,
										string? IpClienteWMask,
										string? Ttk,
										string? FechaSolicitudIng,
										string? FechaRespuestaIng,
										string? DescripOc,
										string? Descripcion,
										string? Estatus,
										string? TipoServicio,
										string? IdGrado,
										string? Template,
										string? UsuarioCreo,
										string? GPON_P2P,
										string? CreateVPN,
										string? RouterRD,
										string? PON,
										string? PosicionOnt,
										string? NombreFactura,
										string? NumeroCuenta,
										string? Plan,
										string? MangaGPON, //GPON
										string? PuertoMG,
										string? CoordenadasClienteY, //Coordenadas Cliente solo para los casos de instalación y traslado
										string? CoordenadasClienteX, //Coordenadas Cliente solo para los casos de instalación y traslado
										string? CoordenadasMangaY, //Coordenadas de Manga solo para GPON
										string? CoordenadasMangaX, //Coordenadas de Manga solo para GPON
										string? Site, //FO P2P
										string? Serial_ONT);
	}
}
